### ISSUE TITLE
Url with protocol prefixed with emoji being incorrectly parsed

### ISSUE THREAD

**Issue by caiofct** [gregjacobs/Autolinker.js#399]
An url like 👍https://www.google.com is being parsed as http://oogle.com/ . If I remove the protocol and just use 
👍www.google.com then it will be parsed correctly http://xn--www-0113b.google.com/.

This can be confirmed using the live demo example: http://greg-jacobs.com/Autolinker.js/examples/live-example/

I believe this could be a regression from https://github.com/gregjacobs/Autolinker.js/pull/276.

**Comment by caiofct** [comment]
@gregjacobs Any chance you could take a look at this one?

**Comment by gregjacobs** [comment]
This is now fixed in 4.0.1. Thanks for reporting!

**Comment by caiofct** [comment]
Hey @gregjacobs I just tried the fixed version 4.0.1 of this library and the reported issue here is still happening. You can see it in the demo page:

👍https://www.google.com => Doesn't work
👍www.google.com => Works
